Fix lighbox when gallery has no siblings
TryGhost/Themes pull request #58
Opened 2021-12-05 13:03 UTC by leoxiong

When a gallery has no siblings (i.e. a page containing only a gallery, or a gallery at the very start/end of a page), clicking to view a gallery image would throw an exception.

See MDN for nextSibling vs nextElementSibling: https://developer.mozilla.org/en-US/docs/Web/API/Node/nextSibling

2021-12-13 05:23 UTC, minimaluminium requested changes
Hey there, nice find, thanks for that! There're a few things to be updated, and should be good to merge 🙂

2021-12-13 05:23 UTC, minimaluminium commented on packages/_shared/assets/js/lib/lightbox.js
> +                prevSibling = prevSibling.previousSibling;
Should be replaced with `previousElementSibling` here.

2021-12-13 05:23 UTC, minimaluminium commented on packages/_shared/assets/js/lib/lightbox.js
> +                nextSibling = nextSibling.nextSibling;
This one should also be `nextElementSibling`.

2021-12-13 11:49 UTC, leoxiong commented
Hey @minimaluminium updated :). Also added the built JS files.

2022-01-03 02:39 UTC, minimaluminium commented
Hey @leoxiong, happy new year! Sorry, I meant changing `prevSibling = prevSibling.previousSibling;` to `prevSibling = prevSibling.previousElementSibling;`, and same for `nextSibling`. The variable names shouldn't be changed :)

2022-01-03 03:01 UTC, closed without merging

2022-01-03 03:04 UTC, minimaluminium commented
@leoxiong I've just closed this one, because it got bit harder to manage. Instead I've fixed the issue in https://github.com/TryGhost/Themes/commit/104133d0fa7ec75ccd2eefba4488a074f8cd74b9, and gave you a credit in the commit. Thank you 🙌

2022-01-03 10:59 UTC, leoxiong commented
No worries, thanks.